//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankHCI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obavjestenja
    {
        public int ObavjestenjeId { get; set; }
        public Nullable<int> KorisnikId { get; set; }
        public Nullable<int> DonatorId { get; set; }
        public System.DateTime DatumObjave { get; set; }
        public string Naslov { get; set; }
        public string Sadrzaj { get; set; }
    
        public virtual Donatori Donatori { get; set; }
        public virtual Korisnici Korisnici { get; set; }
    }
}
