//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankHCI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stanja
    {
        public int StanjeId { get; set; }
        public Nullable<int> TransfuzijskiCentarId { get; set; }
        public string KrvnaGrupa { get; set; }
        public int Kolicina { get; set; }
    
        public virtual TransfuzijskiCentri TransfuzijskiCentri { get; set; }
    }
}
