//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankHCI_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZahtjevZaKrv
    {
        public int ZahtjevZaKrvId { get; set; }
        public Nullable<int> TransfuzijskiCentarId { get; set; }
        public Nullable<int> InstitucijaId { get; set; }
        public string NazivKrvneGrupe { get; set; }
        public int BrojDoza { get; set; }
        public int Kolicina { get; set; }
        public System.DateTime DatumZahtjeva { get; set; }
        public Nullable<int> KorisnikId { get; set; }
        public Nullable<int> StatusZahtjevaId { get; set; }
        public Nullable<int> DonatorId { get; set; }
    
        public virtual Donatori Donatori { get; set; }
        public virtual Institucije Institucije { get; set; }
        public virtual Korisnici Korisnici { get; set; }
        public virtual StatusZahtjeva StatusZahtjeva { get; set; }
        public virtual TransfuzijskiCentri TransfuzijskiCentri { get; set; }
    }
}
